server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://hainguyen@bitbucket.org/hainguyen/mycollab-config-repo.git
          skipSslValidation: true
          username: haiphucnguyen@gmail.com
          password: HaiLinh7980
  security:
    user:
      name: root
      password: esofthead321